### ISSUE TITLE
Does context need to be shared with the whole App?

### ISSUE THREAD

**Issue by Cijin** [triplettrj/buildaport#1]
https://github.com/triplettrj/buildaport/blob/421d02599f121ab5c05ed0124f12208176b45d44/src/index.js#L9

So every time the context value changes the whole App will be re-rendered, see if you can pass the context only to those children that need/use it's value.

**Comment by triplettrj** [comment]
removed context provider from index.js and only wrapped BuyMeABeer and Cart components with context provider
