### ISSUE TITLE
The else here is redundant

### ISSUE THREAD

**Issue by Cijin** [triplettrj/buildaport#2]
https://github.com/triplettrj/buildaport/blob/421d02599f121ab5c05ed0124f12208176b45d44/src/Context.js#L26

You can avoid this `else` by `return`ing early after you set the state.
```js
if (exist) {
  setBeer(beerCart.map( item => item.id === newBeer.id ? {...exist, qty: exist.qty +1} : item)) 
  return
} 
setBeer([...beerCart, {...newBeer, qty: 1}])
```

Same comment for [this line](https://github.com/triplettrj/buildaport/blob/421d02599f121ab5c05ed0124f12208176b45d44/src/Context.js#L31)

**Comment by triplettrj** [comment]
made changes
